import { Recipe, RecipeCategory } from '@/types/recipe'

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    title: "מרק עוף של סבתא",
    description: "מרק עוף מסורתי ומחמם הלב, מושלם לימים קרים ולמפגשים משפחתיים.",
    category: RecipeCategory.SOUP,
    prepTimeMinutes: 20,
    cookTimeMinutes: 90,
    servings: 8,
    ingredients: [
      { order: 1, text: "עוף שלם (1.5-2 ק״ג)" },
      { order: 2, text: "2 בצלים גדולים, חתוכים לרבעים" },
      { order: 3, text: "4 גזרים, חתוכים לקוביות" },
      { order: 4, text: "4 גבעולי סלרי, חתוכים לקוביות" },
      { order: 5, text: "אגודת שמיר טרי" },
      { order: 6, text: "אגודת פטרוזיליה טרייה" },
      { order: 7, text: "מלח ופלפל שחור לפי הטעם" },
      { order: 8, text: "3 ליטר מים" },
    ],
    instructions: [
      { step: 1, text: "מניחים את העוף בסיר גדול ומכסים במים. מביאים לרתיחה." },
      { step: 2, text: "מוסיפים בצלים, גזר וסלרי לסיר." },
      { step: 3, text: "מבשלים על אש נמוכה למשך שעה עד שעה וחצי עד שהעוף רך." },
      { step: 4, text: "מוציאים את העוף ומפרקים את הבשר. מסננים את המרק." },
      { step: 5, text: "מחזירים את בשר העוף המפורק למרק הצלול." },
      { step: 6, text: "מוסיפים עשבי תיבול טריים ומתבלים במלח ופלפל." },
      { step: 7, text: "מבשלים עוד 5 דקות ומגישים חם." },
    ],
    photoUrl: "https://picsum.photos/400/300?random=1",
    tags: ["נוחות", "מסורתי", "בריא", "חורף"],
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2023-12-01'),
    createdBy: "מעיין",
    lastModifiedBy: "מעיין",
  },
  {
    id: '2',
    title: "פלפלים ממולאים ים תיכוניים",
    description: "פלפלים צבעוניים ממולאים באורז, עשבי תיבול ותבלינים ארומטיים.",
    category: RecipeCategory.MAIN,
    prepTimeMinutes: 25,
    cookTimeMinutes: 45,
    servings: 6,
    ingredients: [
      { order: 1, text: "6 פלפלים גדולים (צבעים מעורבים)" },
      { order: 2, text: "כוס וחצי אורז ארוך" },
      { order: 3, text: "בצל גדול, קצוץ דק" },
      { order: 4, text: "3 שיני שום, קצוצות דק" },
      { order: 5, text: "חצי כוס צנוברים" },
      { order: 6, text: "רבע כוס נענע טרייה, קצוצה" },
      { order: 7, text: "רבע כוס פטרוזיליה טרייה, קצוצה" },
      { order: 8, text: "2 עגבניות, קצוצות לקוביות" },
      { order: 9, text: "רבע כוס שמן זית" },
      { order: 10, text: "כפית קינמון" },
      { order: 11, text: "מלח ופלפל לפי הטעם" },
    ],
    instructions: [
      { step: 1, text: "חותכים את החלק העליון של הפלפלים ומוציאים זרעים וקרומים." },
      { step: 2, text: "מטגנים בצל ושום בשמן זית עד שמתרככים." },
      { step: 3, text: "מוסיפים אורז, צנוברים ותבלינים. מטגנים 2 דקות." },
      { step: 4, text: "מוסיפים עגבניות ועשבי תיבול, מערבבים היטב." },
      { step: 5, text: "ממלאים את הפלפלים בתערובת האורז." },
      { step: 6, text: "מניחים בתבנית אפייה עם חצי כוס מים." },
      { step: 7, text: "מכסים ואופים ב-190 מעלות למשך 45 דקות." },
    ],
    photoUrl: "https://picsum.photos/400/300?random=2",
    tags: ["ים תיכוני", "צמחוני", "בריא", "מנה עיקרית"],
    createdAt: new Date('2023-11-15'),
    updatedAt: new Date('2023-11-20'),
    createdBy: "יובל",
    lastModifiedBy: "יובל",
  },
  {
    id: '3',
    title: "בקלווה דבש ושקדים",
    description: "שכבות עדינות של בצק פילו עם אגוזים וסירופ דבש מתוק.",
    category: RecipeCategory.DESSERT,
    prepTimeMinutes: 45,
    cookTimeMinutes: 35,
    servings: 24,
    ingredients: [
      { order: 1, text: "חצי קילו בצק פילו, מופשר" },
      { order: 2, text: "2 כוסות אגוזים מעורבים (אגוזי מלך, שקדים), קצוצים" },
      { order: 3, text: "כוס חמאה, מומסת" },
      { order: 4, text: "כפית קינמון" },
      { order: 5, text: "כוס דבש" },
      { order: 6, text: "3/4 כוס מים" },
      { order: 7, text: "3/4 כוס סוכר" },
      { order: 8, text: "כפית תמצית וניל" },
      { order: 9, text: "מיץ לימון אחד" },
    ],
    instructions: [
      { step: 1, text: "מערבבים אגוזים קצוצים עם קינמון." },
      { step: 2, text: "מניחים חצי מדפי הפילו בתבנית משומנת, משחים כל דף בחמאה." },
      { step: 3, text: "פורסים את תערובת האגוזים באופן שווה על הפילו." },
      { step: 4, text: "מכסים עם שאר דפי הפילו, משחים כל דף." },
      { step: 5, text: "חותכים לצורות יהלום לפני האפייה." },
      { step: 6, text: "אופים ב-175 מעלות למשך 35 דקות עד שמזהיב." },
      { step: 7, text: "בינתיים מכינים סירופ על ידי הרתחת דבש, מים, סוכר, וניל ומיץ לימון." },
      { step: 8, text: "יוצקים סירופ חם על הבקלווה החמה. מקררים לחלוטין לפני ההגשה." },
    ],
    photoUrl: "https://picsum.photos/400/300?random=3",
    tags: ["קינוח", "ים תיכוני", "אגוזים", "אירוע מיוחד"],
    createdAt: new Date('2023-10-30'),
    updatedAt: new Date('2023-11-01'),
    createdBy: "יוסי",
    lastModifiedBy: "יוסי",
  },
]