import { PrismaClient, RecipeCategory } from '@prisma/client'

const prisma = new PrismaClient()

const mockRecipes = [
  {
    title: "עוגת שוקולד של סבתא",
    description: "עוגת שוקולד רכה ועשירה, מתכון מסורתי של המשפחה שעובר מדור לדור",
    category: RecipeCategory.DESSERT,
    prepTimeMinutes: 20,
    cookTimeMinutes: 45,
    servings: 8,
    ingredients: [
      { order: 1, text: "2 כוסות קמח" },
      { order: 2, text: "1.5 כוסות סוכר" },
      { order: 3, text: "3/4 כוס אבקת קקאו" },
      { order: 4, text: "2 כפיות אבקת אפייה" },
      { order: 5, text: "1 כפית מלח" },
      { order: 6, text: "2 ביצים" },
      { order: 7, text: "1 כוס חלב" },
      { order: 8, text: "1/2 כוס שמן" },
      { order: 9, text: "2 כפות תמצית וניל" },
      { order: 10, text: "1 כוס מים רותחים" }
    ],
    instructions: [
      { step: 1, text: "מחממים תנור ל-180 מעלות ומשמנים תבנית עוגה" },
      { step: 2, text: "מערבבים בקערה גדולה את כל החומרים היבשים" },
      { step: 3, text: "בקערה נפרדת מערבבים ביצים, חלב, שמן ווניל" },
      { step: 4, text: "מוסיפים את התערובת הרטובה לחומרים היבשים ומערבבים" },
      { step: 5, text: "מוסיפים מים רותחים בהדרגה תוך כדי ערבוב" },
      { step: 6, text: "יוצקים לתבנית ואופים 35-40 דקות" },
      { step: 7, text: "בודקים עם קיסם שיוצא נקי" },
      { step: 8, text: "מצננים לפני הגשה" }
    ],
    tags: ["קינוח", "שוקולד", "עוגה", "מסורתי", "משפחתי"],
    createdBy: "יעל",
    lastModifiedBy: "יעל",
  },
  {
    title: "חומוס הבית המושלם",
    description: "חומוס קרמי וטעים, הסוד הוא בהכנה הנכונה של החומוס ובתיבול המושלם",
    category: RecipeCategory.APPETIZER,
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    servings: 6,
    ingredients: [
      { order: 1, text: "2 כוסות חומוס מבושל (או משומר)" },
      { order: 2, text: "1/4 כוס טחינה גולמית" },
      { order: 3, text: "2 שיני שום" },
      { order: 4, text: "3 כפות מיץ לימון טרי" },
      { order: 5, text: "1/2 כפית מלח" },
      { order: 6, text: "1/4 כפית כמון" },
      { order: 7, text: "2-3 כפות מים קרים" },
      { order: 8, text: "שמן זית לקישוט" },
      { order: 9, text: "פפריקה לקישוט" },
      { order: 10, text: "פטרוזיליה קצוצה לקישוט" }
    ],
    instructions: [
      { step: 1, text: "שמים בקערת מעבד מזון את החומוס המבושל" },
      { step: 2, text: "מוסיפים טחינה, שום, מיץ לימון, מלח וכמון" },
      { step: 3, text: "מפעילים עד קבלת תערובת חלקה" },
      { step: 4, text: "מוסיפים מים בהדרגה עד קבלת הקשיות הרצויה" },
      { step: 5, text: "טועמים ומתקנים תיבול לפי הטעם" },
      { step: 6, text: "מעבירים לצלחת הגשה" },
      { step: 7, text: "יוצרים גומות עם כף ומוסיפים שמן זית" },
      { step: 8, text: "מפזרים פפריקה ופטרוזיליה" }
    ],
    tags: ["מזרח תיכוני", "טבעוני", "בריא", "מתאבן", "מסורתי"],
    createdBy: "יעל",
    lastModifiedBy: "יעל",
  },
  {
    title: "Honey Almond Baklava",
    description: "Delicate layers of phyllo pastry with nuts and honey syrup.",
    category: RecipeCategory.DESSERT,
    prepTimeMinutes: 45,
    cookTimeMinutes: 35,
    servings: 24,
    ingredients: [
      { order: 1, text: "1 lb phyllo pastry, thawed" },
      { order: 2, text: "2 cups mixed nuts (walnuts, almonds), chopped" },
      { order: 3, text: "1 cup butter, melted" },
      { order: 4, text: "1 tsp cinnamon" },
      { order: 5, text: "1 cup honey" },
      { order: 6, text: "¾ cup water" },
      { order: 7, text: "¾ cup sugar" },
      { order: 8, text: "1 tsp vanilla extract" },
      { order: 9, text: "1 lemon, juiced" },
    ],
    instructions: [
      { step: 1, text: "Mix chopped nuts with cinnamon." },
      { step: 2, text: "Layer half the phyllo sheets in buttered pan, brushing each with butter." },
      { step: 3, text: "Spread nut mixture evenly over phyllo." },
      { step: 4, text: "Top with remaining phyllo, brushing each sheet." },
      { step: 5, text: "Cut into diamond shapes before baking." },
      { step: 6, text: "Bake at 350°F for 35 minutes until golden." },
      { step: 7, text: "Meanwhile, make syrup by boiling honey, water, sugar, vanilla, and lemon juice." },
      { step: 8, text: "Pour warm syrup over hot baklava. Cool completely before serving." },
    ],
    tags: ["dessert", "mediterranean", "nuts", "special occasion"],
    createdBy: "Yael's Grandmother",
    lastModifiedBy: "Yael's Mother",
  },
  {
    title: "Crispy Herb-Crusted Salmon",
    description: "Fresh salmon fillets with a flavorful herb and breadcrumb crust.",
    category: RecipeCategory.MAIN,
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 4,
    ingredients: [
      { order: 1, text: "4 salmon fillets (6 oz each)" },
      { order: 2, text: "1 cup panko breadcrumbs" },
      { order: 3, text: "3 tbsp fresh parsley, chopped" },
      { order: 4, text: "2 tbsp fresh dill, chopped" },
      { order: 5, text: "2 cloves garlic, minced" },
      { order: 6, text: "3 tbsp olive oil" },
      { order: 7, text: "2 tbsp Dijon mustard" },
      { order: 8, text: "1 lemon, zested and juiced" },
      { order: 9, text: "Salt and pepper to taste" },
    ],
    instructions: [
      { step: 1, text: "Preheat oven to 425°F." },
      { step: 2, text: "Mix breadcrumbs, herbs, garlic, olive oil, and lemon zest." },
      { step: 3, text: "Season salmon with salt and pepper." },
      { step: 4, text: "Brush salmon with mustard, then press herb mixture on top." },
      { step: 5, text: "Place on baking sheet lined with parchment." },
      { step: 6, text: "Bake for 12-15 minutes until fish flakes easily." },
      { step: 7, text: "Serve with lemon wedges." },
    ],
    tags: ["fish", "healthy", "quick", "elegant"],
    createdBy: "Yael",
    lastModifiedBy: "Yael",
  },
  {
    title: "Classic Hummus",
    description: "Smooth and creamy homemade hummus that's much better than store-bought.",
    category: RecipeCategory.APPETIZER,
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 8,
    ingredients: [
      { order: 1, text: "2 cups cooked chickpeas (or 1 can, drained)" },
      { order: 2, text: "¼ cup fresh lemon juice" },
      { order: 3, text: "¼ cup tahini" },
      { order: 4, text: "1 small garlic clove, minced" },
      { order: 5, text: "2 tbsp extra-virgin olive oil, plus more for serving" },
      { order: 6, text: "½ tsp ground cumin" },
      { order: 7, text: "Salt to taste" },
      { order: 8, text: "2-3 tbsp water, as needed" },
      { order: 9, text: "Paprika for garnish" },
    ],
    instructions: [
      { step: 1, text: "Combine tahini and lemon juice in food processor. Process for 1 minute." },
      { step: 2, text: "Add olive oil, garlic, cumin, and ½ tsp salt. Process for 30 seconds." },
      { step: 3, text: "Add half the chickpeas and process for 1 minute." },
      { step: 4, text: "Add remaining chickpeas and process until smooth, 1-2 minutes." },
      { step: 5, text: "With processor running, slowly add water until desired consistency." },
      { step: 6, text: "Taste and adjust seasoning." },
      { step: 7, text: "Serve drizzled with olive oil and sprinkled with paprika." },
    ],
    tags: ["appetizer", "vegan", "mediterranean", "healthy"],
    createdBy: "Family Friend",
    lastModifiedBy: "Yael's Mother",
  },
  {
    title: "Chocolate Chip Cookies",
    description: "Soft, chewy chocolate chip cookies that are always a family favorite.",
    category: RecipeCategory.DESSERT,
    prepTimeMinutes: 15,
    cookTimeMinutes: 12,
    servings: 36,
    ingredients: [
      { order: 1, text: "2¼ cups all-purpose flour" },
      { order: 2, text: "1 tsp baking soda" },
      { order: 3, text: "1 tsp salt" },
      { order: 4, text: "1 cup butter, softened" },
      { order: 5, text: "¾ cup granulated sugar" },
      { order: 6, text: "¾ cup packed brown sugar" },
      { order: 7, text: "2 large eggs" },
      { order: 8, text: "2 tsp vanilla extract" },
      { order: 9, text: "2 cups chocolate chips" },
    ],
    instructions: [
      { step: 1, text: "Preheat oven to 375°F." },
      { step: 2, text: "Mix flour, baking soda, and salt in a bowl." },
      { step: 3, text: "Beat butter and both sugars until creamy." },
      { step: 4, text: "Beat in eggs and vanilla." },
      { step: 5, text: "Gradually mix in flour mixture." },
      { step: 6, text: "Stir in chocolate chips." },
      { step: 7, text: "Drop rounded tablespoons onto ungreased baking sheets." },
      { step: 8, text: "Bake 9-11 minutes until golden brown. Cool on wire racks." },
    ],
    tags: ["cookies", "dessert", "family favorite", "chocolate"],
    createdBy: "Yael's Mother",
    lastModifiedBy: "Yael's Mother",
  },
  {
    title: "Roasted Vegetable Couscous",
    description: "A colorful and nutritious side dish with perfectly seasoned vegetables.",
    category: RecipeCategory.SIDE,
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    servings: 6,
    ingredients: [
      { order: 1, text: "1½ cups couscous" },
      { order: 2, text: "2 cups vegetable broth" },
      { order: 3, text: "1 zucchini, diced" },
      { order: 4, text: "1 red bell pepper, diced" },
      { order: 5, text: "1 yellow bell pepper, diced" },
      { order: 6, text: "1 red onion, diced" },
      { order: 7, text: "2 cloves garlic, minced" },
      { order: 8, text: "¼ cup olive oil" },
      { order: 9, text: "1 tsp dried oregano" },
      { order: 10, text: "½ tsp ground cumin" },
      { order: 11, text: "Salt and pepper to taste" },
      { order: 12, text: "¼ cup fresh parsley, chopped" },
    ],
    instructions: [
      { step: 1, text: "Preheat oven to 425°F." },
      { step: 2, text: "Toss vegetables with olive oil, oregano, cumin, salt, and pepper." },
      { step: 3, text: "Spread on baking sheet and roast for 25 minutes." },
      { step: 4, text: "Meanwhile, bring broth to a boil in a saucepan." },
      { step: 5, text: "Stir in couscous, cover, and remove from heat." },
      { step: 6, text: "Let stand 5 minutes, then fluff with a fork." },
      { step: 7, text: "Mix roasted vegetables into couscous." },
      { step: 8, text: "Garnish with fresh parsley before serving." },
    ],
    tags: ["vegetarian", "side dish", "healthy", "colorful"],
    createdBy: "Yael",
    lastModifiedBy: "Yael",
  },
  {
    title: "Traditional Matzo Ball Soup",
    description: "Light, fluffy matzo balls in rich chicken broth - perfect for holidays.",
    category: RecipeCategory.SOUP,
    prepTimeMinutes: 30,
    cookTimeMinutes: 40,
    servings: 8,
    ingredients: [
      { order: 1, text: "4 large eggs" },
      { order: 2, text: "¼ cup schmaltz or vegetable oil" },
      { order: 3, text: "1 cup matzo meal" },
      { order: 4, text: "¼ cup warm water or broth" },
      { order: 5, text: "1 tsp salt" },
      { order: 6, text: "8 cups rich chicken broth" },
      { order: 7, text: "2 carrots, sliced" },
      { order: 8, text: "2 celery stalks, sliced" },
      { order: 9, text: "Fresh dill for garnish" },
    ],
    instructions: [
      { step: 1, text: "Beat eggs and oil in a large bowl." },
      { step: 2, text: "Stir in matzo meal, water, and salt until combined." },
      { step: 3, text: "Refrigerate mixture for at least 30 minutes." },
      { step: 4, text: "Bring a large pot of salted water to boil." },
      { step: 5, text: "With wet hands, form mixture into walnut-sized balls." },
      { step: 6, text: "Drop balls into boiling water and simmer 20 minutes." },
      { step: 7, text: "Heat chicken broth with carrots and celery." },
      { step: 8, text: "Add cooked matzo balls to hot broth and serve with dill." },
    ],
    tags: ["traditional", "jewish", "holiday", "comfort food"],
    createdBy: "Yael's Grandmother",
    lastModifiedBy: "Yael's Mother",
  },
  {
    title: "Fresh Berry Smoothie Bowl",
    description: "A refreshing and healthy breakfast bowl topped with fresh fruits and nuts.",
    category: RecipeCategory.SNACK,
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 2,
    ingredients: [
      { order: 1, text: "1 frozen banana, sliced" },
      { order: 2, text: "1 cup frozen mixed berries" },
      { order: 3, text: "½ cup Greek yogurt" },
      { order: 4, text: "¼ cup almond milk" },
      { order: 5, text: "1 tbsp honey" },
      { order: 6, text: "¼ cup granola" },
      { order: 7, text: "2 tbsp sliced almonds" },
      { order: 8, text: "Fresh berries for topping" },
      { order: 9, text: "1 tbsp chia seeds" },
    ],
    instructions: [
      { step: 1, text: "Blend frozen banana, berries, yogurt, almond milk, and honey until smooth." },
      { step: 2, text: "Pour into two bowls." },
      { step: 3, text: "Top with granola, almonds, fresh berries, and chia seeds." },
      { step: 4, text: "Serve immediately while cold." },
    ],
    tags: ["healthy", "breakfast", "smoothie", "antioxidants"],
    createdBy: "Yael",
    lastModifiedBy: "Yael",
  },
  {
    title: "Spiced Chai Latte",
    description: "Homemade chai with warming spices - much better than coffee shop versions.",
    category: RecipeCategory.BEVERAGE,
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    servings: 4,
    ingredients: [
      { order: 1, text: "4 cups water" },
      { order: 2, text: "4 black tea bags or 4 tsp loose tea" },
      { order: 3, text: "1 cinnamon stick" },
      { order: 4, text: "6 cardamom pods, lightly crushed" },
      { order: 5, text: "4 cloves" },
      { order: 6, text: "1 inch fresh ginger, sliced" },
      { order: 7, text: "1 cup whole milk" },
      { order: 8, text: "3 tbsp honey or sugar" },
      { order: 9, text: "Pinch of black pepper" },
    ],
    instructions: [
      { step: 1, text: "Bring water to boil with all spices." },
      { step: 2, text: "Reduce heat and simmer for 10 minutes." },
      { step: 3, text: "Add tea bags and steep for 3-4 minutes." },
      { step: 4, text: "Add milk and honey, heat until steaming." },
      { step: 5, text: "Strain through fine mesh strainer." },
      { step: 6, text: "Serve hot in mugs." },
    ],
    tags: ["beverage", "spiced", "warming", "cozy"],
    createdBy: "Family Friend",
    lastModifiedBy: "Yael",
  },
]

async function main() {
  console.log('Starting seed...')

  // Clear existing recipes
  await prisma.recipe.deleteMany()

  // Create mock recipes
  for (const recipe of mockRecipes) {
    await prisma.recipe.create({
      data: recipe,
    })
  }

  console.log(`Created ${mockRecipes.length} recipes`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })